apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-ses-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: aws-ses
  template:
    metadata:
      labels:
        deployment: aws-ses
    spec:
      containers:
        - name: xapi-notification-service
          image: chathuru/springboot-aws-ses:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      serviceAccountName: notification

---
apiVersion: v1
kind: Service
metadata:
  name: aws-ses-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    deployment: aws-ses
