name: Build and Deploy to maven repository

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Package Build
        if: success()
        run: mvn clean install

      - name: Generate Dependency List
        if: success()
        run: mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

      - name: Docker Build & Push
        if: success()
        run: |
          docker build . -t chathuru/springboot-aws-s3
          docker push chathuru/springboot-aws-s3
